from tests.demo.page import LoginPage,HomePage,ProductPage,BackendPage,BrandPage,LogoutPage,SuccessfulPage,\
    ResultPage,RegionPage,CreatePage,NonePage,OrderPage,IssuePage,AdminPage,KeywordPage
from graphviz import Digraph
dot = Digraph(name='navgarph',comment='first draw')
dot.node('1',LoginPage.name)
dot.node('2',HomePage.name)
dot.node('3',ProductPage.name)
dot.node('4',HomePage.name)
dot.node('5',ProductPage.name)
dot.node('6',BackendPage.name)
dot.node('7',BrandPage.name)
dot.node('8',LogoutPage.name)
dot.node('9',SuccessfulPage.name)
dot.node('A',ResultPage.name)
dot.node('B',RegionPage.name)
dot.node('C',CreatePage.name)
dot.node('D',NonePage.name)
dot.node('E',OrderPage.name)
dot.node('F',IssuePage.name)
dot.node('G',AdminPage.name)
dot.node('H',KeywordPage.name)
dot.edges(['12','4B','47','4E','4F','4H','4G','4C','BA'])
#dot.edge('B','A','back')
print(dot.source)
dot.render('test-output/test-table.gv', view=True)