"""modify info

Revision ID: 2a82b8cad235
Revises: 6d2cdd0601cf
Create Date: 2020-04-24 20:36:09.269044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a82b8cad235'
down_revision = '6d2cdd0601cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('graph_path', sa.String(length=128), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('pages', 'graph_path')
    # ### end Alembic commands ###
