"""add graph

Revision ID: 524836f59748
Revises: 2a82b8cad235
Create Date: 2020-04-25 10:31:06.719157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524836f59748'
down_revision = '2a82b8cad235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagename', sa.String(length=32), nullable=True),
    sa.Column('pog', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphs_pagename'), 'graphs', ['pagename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graphs_pagename'), table_name='graphs')
    op.drop_table('graphs')
    # ### end Alembic commands ###
